version: "3.8"

services:
  flyover-teaching:
    build: .
    container_name: flyover-teaching
    ports:
      - "5000:80"
      - "5001:443"
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - TZ=America/Chicago
    volumes:
      - /srv/docker_data/flyover_teaching/data:/app/data
      - /srv/docker_data/flyover_teaching/logs:/app/logs
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flyover.rule=Host(`flyover.local`)"
      - "traefik.http.services.flyover.loadbalancer.server.port=80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: flyover_teaching_network
    driver: bridge